# Generated by Django 2.0.4 on 2018-04-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultryApp', '0011_auto_20180308_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Restart_time',
        ),
    ]
